version: '2'
services:
  standarddemoaplication-app:
    image: standarddemoaplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mariadb://standarddemoaplication-mariadb:3306/standarddemoaplication
      - JHIPSTER_CACHE_REDIS_SERVER=redis://standarddemoaplication-redis:6379
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://standarddemoaplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://standarddemoaplication-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
  standarddemoaplication-mariadb:
    extends:
      file: mariadb.yml
      service: standarddemoaplication-mariadb
  standarddemoaplication-redis:
    extends:
      file: redis.yml
      service: standarddemoaplication-redis
  standarddemoaplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: standarddemoaplication-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
